import type { Stock } from "@/types";

// S&P 500 constituents (point-in-time snapshot). US stocks are plain Yahoo
// tickers (full OHLC history → Fibonacci works), so no TradingView scanner is
// needed. Refresh from:
// https://github.com/datasets/s-and-p-500-companies/blob/main/data/constituents.csv

function us(symbol: string, name: string, sector: string): Stock {
  return {
    symbol,
    // Yahoo uses a dash for class shares: BRK.B -> BRK-B, BF.B -> BF-B.
    yahooSymbol: symbol.split(".").join("-"),
    // TradingView resolves bare US tickers (incl. dotted class shares).
    tvSymbol: symbol,
    exchange: "US",
    marketId: "US",
    name,
    sector,
  };
}

export const SPX_UNIVERSE: Stock[] = [
  us("MMM", "3M", "Industrials"),
  us("AOS", "A. O. Smith", "Industrials"),
  us("ABT", "Abbott Laboratories", "Health Care"),
  us("ABBV", "AbbVie", "Health Care"),
  us("ACN", "Accenture", "Information Technology"),
  us("ADBE", "Adobe Inc.", "Information Technology"),
  us("AMD", "Advanced Micro Devices", "Information Technology"),
  us("AES", "AES Corporation", "Utilities"),
  us("AFL", "Aflac", "Financials"),
  us("A", "Agilent Technologies", "Health Care"),
  us("APD", "Air Products", "Materials"),
  us("ABNB", "Airbnb", "Consumer Discretionary"),
  us("AKAM", "Akamai Technologies", "Information Technology"),
  us("ALB", "Albemarle Corporation", "Materials"),
  us("ARE", "Alexandria Real Estate Equities", "Real Estate"),
  us("ALGN", "Align Technology", "Health Care"),
  us("ALLE", "Allegion", "Industrials"),
  us("LNT", "Alliant Energy", "Utilities"),
  us("ALL", "Allstate", "Financials"),
  us("GOOGL", "Alphabet Inc. (Class A)", "Communication Services"),
  us("GOOG", "Alphabet Inc. (Class C)", "Communication Services"),
  us("MO", "Altria", "Consumer Staples"),
  us("AMZN", "Amazon", "Consumer Discretionary"),
  us("AMCR", "Amcor", "Materials"),
  us("AEE", "Ameren", "Utilities"),
  us("AEP", "American Electric Power", "Utilities"),
  us("AXP", "American Express", "Financials"),
  us("AIG", "American International Group", "Financials"),
  us("AMT", "American Tower", "Real Estate"),
  us("AWK", "American Water Works", "Utilities"),
  us("AMP", "Ameriprise Financial", "Financials"),
  us("AME", "Ametek", "Industrials"),
  us("AMGN", "Amgen", "Health Care"),
  us("APH", "Amphenol", "Information Technology"),
  us("ADI", "Analog Devices", "Information Technology"),
  us("AON", "Aon plc", "Financials"),
  us("APA", "APA Corporation", "Energy"),
  us("APO", "Apollo Global Management", "Financials"),
  us("AAPL", "Apple Inc.", "Information Technology"),
  us("AMAT", "Applied Materials", "Information Technology"),
  us("APP", "AppLovin", "Information Technology"),
  us("APTV", "Aptiv", "Consumer Discretionary"),
  us("ACGL", "Arch Capital Group", "Financials"),
  us("ADM", "Archer Daniels Midland", "Consumer Staples"),
  us("ARES", "Ares Management", "Financials"),
  us("ANET", "Arista Networks", "Information Technology"),
  us("AJG", "Arthur J. Gallagher & Co.", "Financials"),
  us("AIZ", "Assurant", "Financials"),
  us("T", "AT&T", "Communication Services"),
  us("ATO", "Atmos Energy", "Utilities"),
  us("ADSK", "Autodesk", "Information Technology"),
  us("ADP", "Automatic Data Processing", "Industrials"),
  us("AZO", "AutoZone", "Consumer Discretionary"),
  us("AVB", "AvalonBay Communities", "Real Estate"),
  us("AVY", "Avery Dennison", "Materials"),
  us("AXON", "Axon Enterprise", "Industrials"),
  us("BKR", "Baker Hughes", "Energy"),
  us("BALL", "Ball Corporation", "Materials"),
  us("BAC", "Bank of America", "Financials"),
  us("BAX", "Baxter International", "Health Care"),
  us("BDX", "Becton Dickinson", "Health Care"),
  us("BRK.B", "Berkshire Hathaway", "Financials"),
  us("BBY", "Best Buy", "Consumer Discretionary"),
  us("TECH", "Bio-Techne", "Health Care"),
  us("BIIB", "Biogen", "Health Care"),
  us("BLK", "BlackRock", "Financials"),
  us("BX", "Blackstone Inc.", "Financials"),
  us("XYZ", "Block, Inc.", "Financials"),
  us("BNY", "BNY Mellon", "Financials"),
  us("BA", "Boeing", "Industrials"),
  us("BKNG", "Booking Holdings", "Consumer Discretionary"),
  us("BSX", "Boston Scientific", "Health Care"),
  us("BMY", "Bristol Myers Squibb", "Health Care"),
  us("AVGO", "Broadcom", "Information Technology"),
  us("BR", "Broadridge Financial Solutions", "Industrials"),
  us("BRO", "Brown & Brown", "Financials"),
  us("BF.B", "Brown–Forman", "Consumer Staples"),
  us("BLDR", "Builders FirstSource", "Industrials"),
  us("BG", "Bunge Global", "Consumer Staples"),
  us("BXP", "BXP, Inc.", "Real Estate"),
  us("CHRW", "C.H. Robinson", "Industrials"),
  us("CDNS", "Cadence Design Systems", "Information Technology"),
  us("CPT", "Camden Property Trust", "Real Estate"),
  us("CPB", "Campbell's Company (The)", "Consumer Staples"),
  us("COF", "Capital One", "Financials"),
  us("CAH", "Cardinal Health", "Health Care"),
  us("CCL", "Carnival Corporation", "Consumer Discretionary"),
  us("CARR", "Carrier Global", "Industrials"),
  us("CVNA", "Carvana", "Consumer Discretionary"),
  us("CASY", "Casey's", "Consumer Staples"),
  us("CAT", "Caterpillar Inc.", "Industrials"),
  us("CBOE", "Cboe Global Markets", "Financials"),
  us("CBRE", "CBRE Group", "Real Estate"),
  us("CDW", "CDW Corporation", "Information Technology"),
  us("COR", "Cencora", "Health Care"),
  us("CNC", "Centene Corporation", "Health Care"),
  us("CNP", "CenterPoint Energy", "Utilities"),
  us("CF", "CF Industries", "Materials"),
  us("CRL", "Charles River Laboratories", "Health Care"),
  us("SCHW", "Charles Schwab Corporation", "Financials"),
  us("CHTR", "Charter Communications", "Communication Services"),
  us("CVX", "Chevron Corporation", "Energy"),
  us("CMG", "Chipotle Mexican Grill", "Consumer Discretionary"),
  us("CB", "Chubb Limited", "Financials"),
  us("CHD", "Church & Dwight", "Consumer Staples"),
  us("CIEN", "Ciena", "Information Technology"),
  us("CI", "Cigna", "Health Care"),
  us("CINF", "Cincinnati Financial", "Financials"),
  us("CTAS", "Cintas", "Industrials"),
  us("CSCO", "Cisco", "Information Technology"),
  us("C", "Citigroup", "Financials"),
  us("CFG", "Citizens Financial Group", "Financials"),
  us("CLX", "Clorox", "Consumer Staples"),
  us("CME", "CME Group", "Financials"),
  us("CMS", "CMS Energy", "Utilities"),
  us("KO", "Coca-Cola Company (The)", "Consumer Staples"),
  us("CTSH", "Cognizant", "Information Technology"),
  us("COHR", "Coherent Corp.", "Information Technology"),
  us("COIN", "Coinbase", "Financials"),
  us("CL", "Colgate-Palmolive", "Consumer Staples"),
  us("CMCSA", "Comcast", "Communication Services"),
  us("FIX", "Comfort Systems USA", "Industrials"),
  us("CAG", "Conagra Brands", "Consumer Staples"),
  us("COP", "ConocoPhillips", "Energy"),
  us("ED", "Consolidated Edison", "Utilities"),
  us("STZ", "Constellation Brands", "Consumer Staples"),
  us("CEG", "Constellation Energy", "Utilities"),
  us("COO", "Cooper Companies (The)", "Health Care"),
  us("CPRT", "Copart", "Industrials"),
  us("GLW", "Corning Inc.", "Information Technology"),
  us("CPAY", "Corpay", "Financials"),
  us("CTVA", "Corteva", "Materials"),
  us("CSGP", "CoStar Group", "Real Estate"),
  us("COST", "Costco", "Consumer Staples"),
  us("CRH", "CRH plc", "Materials"),
  us("CRWD", "CrowdStrike", "Information Technology"),
  us("CCI", "Crown Castle", "Real Estate"),
  us("CSX", "CSX Corporation", "Industrials"),
  us("CMI", "Cummins", "Industrials"),
  us("CVS", "CVS Health", "Health Care"),
  us("DHR", "Danaher Corporation", "Health Care"),
  us("DRI", "Darden Restaurants", "Consumer Discretionary"),
  us("DDOG", "Datadog", "Information Technology"),
  us("DVA", "DaVita", "Health Care"),
  us("DECK", "Deckers Brands", "Consumer Discretionary"),
  us("DE", "Deere & Company", "Industrials"),
  us("DELL", "Dell Technologies", "Information Technology"),
  us("DAL", "Delta Air Lines", "Industrials"),
  us("DVN", "Devon Energy", "Energy"),
  us("DXCM", "Dexcom", "Health Care"),
  us("FANG", "Diamondback Energy", "Energy"),
  us("DLR", "Digital Realty", "Real Estate"),
  us("DG", "Dollar General", "Consumer Staples"),
  us("DLTR", "Dollar Tree", "Consumer Staples"),
  us("D", "Dominion Energy", "Utilities"),
  us("DPZ", "Domino's", "Consumer Discretionary"),
  us("DASH", "DoorDash", "Consumer Discretionary"),
  us("DOV", "Dover Corporation", "Industrials"),
  us("DOW", "Dow Inc.", "Materials"),
  us("DHI", "D. R. Horton", "Consumer Discretionary"),
  us("DTE", "DTE Energy", "Utilities"),
  us("DUK", "Duke Energy", "Utilities"),
  us("DD", "DuPont", "Materials"),
  us("ETN", "Eaton Corporation", "Industrials"),
  us("EBAY", "eBay Inc.", "Consumer Discretionary"),
  us("SATS", "EchoStar", "Communication Services"),
  us("ECL", "Ecolab", "Materials"),
  us("EIX", "Edison International", "Utilities"),
  us("EW", "Edwards Lifesciences", "Health Care"),
  us("EA", "Electronic Arts", "Communication Services"),
  us("ELV", "Elevance Health", "Health Care"),
  us("EME", "Emcor", "Industrials"),
  us("EMR", "Emerson Electric", "Industrials"),
  us("ETR", "Entergy", "Utilities"),
  us("EOG", "EOG Resources", "Energy"),
  us("EQT", "EQT Corporation", "Energy"),
  us("EFX", "Equifax", "Industrials"),
  us("EQIX", "Equinix", "Real Estate"),
  us("EQR", "Equity Residential", "Real Estate"),
  us("ERIE", "Erie Indemnity", "Financials"),
  us("ESS", "Essex Property Trust", "Real Estate"),
  us("EL", "Estée Lauder Companies (The)", "Consumer Staples"),
  us("EG", "Everest Group", "Financials"),
  us("EVRG", "Evergy", "Utilities"),
  us("ES", "Eversource Energy", "Utilities"),
  us("EXC", "Exelon", "Utilities"),
  us("EXE", "Expand Energy", "Energy"),
  us("EXPE", "Expedia Group", "Consumer Discretionary"),
  us("EXPD", "Expeditors International", "Industrials"),
  us("EXR", "Extra Space Storage", "Real Estate"),
  us("XOM", "ExxonMobil", "Energy"),
  us("FFIV", "F5, Inc.", "Information Technology"),
  us("FDS", "FactSet", "Financials"),
  us("FICO", "Fair Isaac", "Information Technology"),
  us("FAST", "Fastenal", "Industrials"),
  us("FRT", "Federal Realty Investment Trust", "Real Estate"),
  us("FDX", "FedEx", "Industrials"),
  us("FDXF", "FedEx Freight", "Industrials"),
  us("FIS", "Fidelity National Information Services", "Financials"),
  us("FITB", "Fifth Third Bancorp", "Financials"),
  us("FSLR", "First Solar", "Information Technology"),
  us("FE", "FirstEnergy", "Utilities"),
  us("FISV", "Fiserv", "Financials"),
  us("F", "Ford Motor Company", "Consumer Discretionary"),
  us("FTNT", "Fortinet", "Information Technology"),
  us("FTV", "Fortive", "Industrials"),
  us("FOXA", "Fox Corporation (Class A)", "Communication Services"),
  us("FOX", "Fox Corporation (Class B)", "Communication Services"),
  us("BEN", "Franklin Resources", "Financials"),
  us("FCX", "Freeport-McMoRan", "Materials"),
  us("GRMN", "Garmin", "Consumer Discretionary"),
  us("IT", "Gartner", "Information Technology"),
  us("GE", "GE Aerospace", "Industrials"),
  us("GEHC", "GE HealthCare", "Health Care"),
  us("GEV", "GE Vernova", "Industrials"),
  us("GEN", "Gen Digital", "Information Technology"),
  us("GNRC", "Generac", "Industrials"),
  us("GD", "General Dynamics", "Industrials"),
  us("GIS", "General Mills", "Consumer Staples"),
  us("GM", "General Motors", "Consumer Discretionary"),
  us("GPC", "Genuine Parts Company", "Consumer Discretionary"),
  us("GILD", "Gilead Sciences", "Health Care"),
  us("GPN", "Global Payments", "Financials"),
  us("GL", "Globe Life", "Financials"),
  us("GDDY", "GoDaddy", "Information Technology"),
  us("GS", "Goldman Sachs", "Financials"),
  us("HAL", "Halliburton", "Energy"),
  us("HIG", "Hartford (The)", "Financials"),
  us("HAS", "Hasbro", "Consumer Discretionary"),
  us("HCA", "HCA Healthcare", "Health Care"),
  us("DOC", "Healthpeak Properties", "Real Estate"),
  us("HSIC", "Henry Schein", "Health Care"),
  us("HSY", "Hershey Company (The)", "Consumer Staples"),
  us("HPE", "Hewlett Packard Enterprise", "Information Technology"),
  us("HLT", "Hilton Worldwide", "Consumer Discretionary"),
  us("HD", "Home Depot (The)", "Consumer Discretionary"),
  us("HON", "Honeywell", "Industrials"),
  us("HRL", "Hormel Foods", "Consumer Staples"),
  us("HST", "Host Hotels & Resorts", "Real Estate"),
  us("HWM", "Howmet Aerospace", "Industrials"),
  us("HPQ", "HP Inc.", "Information Technology"),
  us("HUBB", "Hubbell Incorporated", "Industrials"),
  us("HUM", "Humana", "Health Care"),
  us("HBAN", "Huntington Bancshares", "Financials"),
  us("HII", "Huntington Ingalls Industries", "Industrials"),
  us("IBM", "IBM", "Information Technology"),
  us("IEX", "IDEX Corporation", "Industrials"),
  us("IDXX", "Idexx Laboratories", "Health Care"),
  us("ITW", "Illinois Tool Works", "Industrials"),
  us("INCY", "Incyte", "Health Care"),
  us("IR", "Ingersoll Rand", "Industrials"),
  us("PODD", "Insulet Corporation", "Health Care"),
  us("INTC", "Intel", "Information Technology"),
  us("IBKR", "Interactive Brokers", "Financials"),
  us("ICE", "Intercontinental Exchange", "Financials"),
  us("IFF", "International Flavors & Fragrances", "Materials"),
  us("IP", "International Paper", "Materials"),
  us("INTU", "Intuit", "Information Technology"),
  us("ISRG", "Intuitive Surgical", "Health Care"),
  us("IVZ", "Invesco", "Financials"),
  us("INVH", "Invitation Homes", "Real Estate"),
  us("IQV", "IQVIA", "Health Care"),
  us("IRM", "Iron Mountain", "Real Estate"),
  us("JBHT", "J.B. Hunt", "Industrials"),
  us("JBL", "Jabil", "Information Technology"),
  us("JKHY", "Jack Henry & Associates", "Financials"),
  us("J", "Jacobs Solutions", "Industrials"),
  us("JNJ", "Johnson & Johnson", "Health Care"),
  us("JCI", "Johnson Controls", "Industrials"),
  us("JPM", "JPMorgan Chase", "Financials"),
  us("KVUE", "Kenvue", "Consumer Staples"),
  us("KDP", "Keurig Dr Pepper", "Consumer Staples"),
  us("KEY", "KeyCorp", "Financials"),
  us("KEYS", "Keysight Technologies", "Information Technology"),
  us("KMB", "Kimberly-Clark", "Consumer Staples"),
  us("KIM", "Kimco Realty", "Real Estate"),
  us("KMI", "Kinder Morgan", "Energy"),
  us("KKR", "KKR & Co.", "Financials"),
  us("KLAC", "KLA Corporation", "Information Technology"),
  us("KHC", "Kraft Heinz", "Consumer Staples"),
  us("KR", "Kroger", "Consumer Staples"),
  us("LHX", "L3Harris", "Industrials"),
  us("LH", "Labcorp", "Health Care"),
  us("LRCX", "Lam Research", "Information Technology"),
  us("LVS", "Las Vegas Sands", "Consumer Discretionary"),
  us("LDOS", "Leidos", "Industrials"),
  us("LEN", "Lennar", "Consumer Discretionary"),
  us("LII", "Lennox International", "Industrials"),
  us("LLY", "Lilly (Eli)", "Health Care"),
  us("LIN", "Linde plc", "Materials"),
  us("LYV", "Live Nation Entertainment", "Communication Services"),
  us("LMT", "Lockheed Martin", "Industrials"),
  us("L", "Loews Corporation", "Financials"),
  us("LOW", "Lowe's", "Consumer Discretionary"),
  us("LULU", "Lululemon Athletica", "Consumer Discretionary"),
  us("LITE", "Lumentum", "Information Technology"),
  us("LYB", "LyondellBasell", "Materials"),
  us("MTB", "M&T Bank", "Financials"),
  us("MPC", "Marathon Petroleum", "Energy"),
  us("MAR", "Marriott International", "Consumer Discretionary"),
  us("MRSH", "Marsh McLennan", "Financials"),
  us("MLM", "Martin Marietta Materials", "Materials"),
  us("MAS", "Masco", "Industrials"),
  us("MA", "Mastercard", "Financials"),
  us("MKC", "McCormick & Company", "Consumer Staples"),
  us("MCD", "McDonald's", "Consumer Discretionary"),
  us("MCK", "McKesson Corporation", "Health Care"),
  us("MDT", "Medtronic", "Health Care"),
  us("MRK", "Merck & Co.", "Health Care"),
  us("META", "Meta Platforms", "Communication Services"),
  us("MET", "MetLife", "Financials"),
  us("MTD", "Mettler Toledo", "Health Care"),
  us("MGM", "MGM Resorts", "Consumer Discretionary"),
  us("MCHP", "Microchip Technology", "Information Technology"),
  us("MU", "Micron Technology", "Information Technology"),
  us("MSFT", "Microsoft", "Information Technology"),
  us("MAA", "Mid-America Apartment Communities", "Real Estate"),
  us("MRNA", "Moderna", "Health Care"),
  us("TAP", "Molson Coors Beverage Company", "Consumer Staples"),
  us("MDLZ", "Mondelez International", "Consumer Staples"),
  us("MPWR", "Monolithic Power Systems", "Information Technology"),
  us("MNST", "Monster Beverage", "Consumer Staples"),
  us("MCO", "Moody's Corporation", "Financials"),
  us("MS", "Morgan Stanley", "Financials"),
  us("MOS", "Mosaic Company (The)", "Materials"),
  us("MSI", "Motorola Solutions", "Information Technology"),
  us("MSCI", "MSCI Inc.", "Financials"),
  us("NDAQ", "Nasdaq, Inc.", "Financials"),
  us("NTAP", "NetApp", "Information Technology"),
  us("NFLX", "Netflix", "Communication Services"),
  us("NEM", "Newmont", "Materials"),
  us("NWSA", "News Corp (Class A)", "Communication Services"),
  us("NWS", "News Corp (Class B)", "Communication Services"),
  us("NEE", "NextEra Energy", "Utilities"),
  us("NKE", "Nike, Inc.", "Consumer Discretionary"),
  us("NI", "NiSource", "Utilities"),
  us("NDSN", "Nordson Corporation", "Industrials"),
  us("NSC", "Norfolk Southern", "Industrials"),
  us("NTRS", "Northern Trust", "Financials"),
  us("NOC", "Northrop Grumman", "Industrials"),
  us("NCLH", "Norwegian Cruise Line Holdings", "Consumer Discretionary"),
  us("NRG", "NRG Energy", "Utilities"),
  us("NUE", "Nucor", "Materials"),
  us("NVDA", "Nvidia", "Information Technology"),
  us("NVR", "NVR, Inc.", "Consumer Discretionary"),
  us("NXPI", "NXP Semiconductors", "Information Technology"),
  us("ORLY", "O’Reilly Automotive", "Consumer Discretionary"),
  us("OXY", "Occidental Petroleum", "Energy"),
  us("ODFL", "Old Dominion", "Industrials"),
  us("OMC", "Omnicom Group", "Communication Services"),
  us("ON", "ON Semiconductor", "Information Technology"),
  us("OKE", "Oneok", "Energy"),
  us("ORCL", "Oracle Corporation", "Information Technology"),
  us("OTIS", "Otis Worldwide", "Industrials"),
  us("PCAR", "Paccar", "Industrials"),
  us("PKG", "Packaging Corporation of America", "Materials"),
  us("PLTR", "Palantir Technologies", "Information Technology"),
  us("PANW", "Palo Alto Networks", "Information Technology"),
  us("PSKY", "Paramount Skydance Corporation", "Communication Services"),
  us("PH", "Parker Hannifin", "Industrials"),
  us("PAYX", "Paychex", "Industrials"),
  us("PYPL", "PayPal", "Financials"),
  us("PNR", "Pentair", "Industrials"),
  us("PEP", "PepsiCo", "Consumer Staples"),
  us("PFE", "Pfizer", "Health Care"),
  us("PCG", "PG&E Corporation", "Utilities"),
  us("PM", "Philip Morris International", "Consumer Staples"),
  us("PSX", "Phillips 66", "Energy"),
  us("PNW", "Pinnacle West Capital", "Utilities"),
  us("PNC", "PNC Financial Services", "Financials"),
  us("POOL", "Pool Corporation", "Consumer Discretionary"),
  us("PPG", "PPG Industries", "Materials"),
  us("PPL", "PPL Corporation", "Utilities"),
  us("PFG", "Principal Financial Group", "Financials"),
  us("PG", "Procter & Gamble", "Consumer Staples"),
  us("PGR", "Progressive Corporation", "Financials"),
  us("PLD", "Prologis", "Real Estate"),
  us("PRU", "Prudential Financial", "Financials"),
  us("PEG", "Public Service Enterprise Group", "Utilities"),
  us("PTC", "PTC Inc.", "Information Technology"),
  us("PSA", "Public Storage", "Real Estate"),
  us("PHM", "PulteGroup", "Consumer Discretionary"),
  us("PWR", "Quanta Services", "Industrials"),
  us("QCOM", "Qualcomm", "Information Technology"),
  us("DGX", "Quest Diagnostics", "Health Care"),
  us("Q", "Qnity Electronics", "Information Technology"),
  us("RL", "Ralph Lauren Corporation", "Consumer Discretionary"),
  us("RJF", "Raymond James Financial", "Financials"),
  us("RTX", "RTX Corporation", "Industrials"),
  us("O", "Realty Income", "Real Estate"),
  us("REG", "Regency Centers", "Real Estate"),
  us("REGN", "Regeneron Pharmaceuticals", "Health Care"),
  us("RF", "Regions Financial Corporation", "Financials"),
  us("RSG", "Republic Services", "Industrials"),
  us("RMD", "ResMed", "Health Care"),
  us("RVTY", "Revvity", "Health Care"),
  us("HOOD", "Robinhood Markets", "Financials"),
  us("ROK", "Rockwell Automation", "Industrials"),
  us("ROL", "Rollins, Inc.", "Industrials"),
  us("ROP", "Roper Technologies", "Information Technology"),
  us("ROST", "Ross Stores", "Consumer Discretionary"),
  us("RCL", "Royal Caribbean Group", "Consumer Discretionary"),
  us("SPGI", "S&P Global", "Financials"),
  us("CRM", "Salesforce", "Information Technology"),
  us("SNDK", "Sandisk", "Information Technology"),
  us("SBAC", "SBA Communications", "Real Estate"),
  us("SLB", "Schlumberger", "Energy"),
  us("STX", "Seagate Technology", "Information Technology"),
  us("SRE", "Sempra", "Utilities"),
  us("NOW", "ServiceNow", "Information Technology"),
  us("SHW", "Sherwin-Williams", "Materials"),
  us("SPG", "Simon Property Group", "Real Estate"),
  us("SWKS", "Skyworks Solutions", "Information Technology"),
  us("SJM", "J.M. Smucker Company (The)", "Consumer Staples"),
  us("SW", "Smurfit Westrock", "Materials"),
  us("SNA", "Snap-on", "Industrials"),
  us("SOLV", "Solventum", "Health Care"),
  us("SO", "Southern Company", "Utilities"),
  us("LUV", "Southwest Airlines", "Industrials"),
  us("SWK", "Stanley Black & Decker", "Industrials"),
  us("SBUX", "Starbucks", "Consumer Discretionary"),
  us("STT", "State Street Corporation", "Financials"),
  us("STLD", "Steel Dynamics", "Materials"),
  us("STE", "Steris", "Health Care"),
  us("SYK", "Stryker Corporation", "Health Care"),
  us("SMCI", "Supermicro", "Information Technology"),
  us("SYF", "Synchrony Financial", "Financials"),
  us("SNPS", "Synopsys", "Information Technology"),
  us("SYY", "Sysco", "Consumer Staples"),
  us("TMUS", "T-Mobile US", "Communication Services"),
  us("TROW", "T. Rowe Price", "Financials"),
  us("TTWO", "Take-Two Interactive", "Communication Services"),
  us("TPR", "Tapestry, Inc.", "Consumer Discretionary"),
  us("TRGP", "Targa Resources", "Energy"),
  us("TGT", "Target Corporation", "Consumer Staples"),
  us("TEL", "TE Connectivity", "Information Technology"),
  us("TDY", "Teledyne Technologies", "Information Technology"),
  us("TER", "Teradyne", "Information Technology"),
  us("TSLA", "Tesla, Inc.", "Consumer Discretionary"),
  us("TXN", "Texas Instruments", "Information Technology"),
  us("TPL", "Texas Pacific Land Corporation", "Energy"),
  us("TXT", "Textron", "Industrials"),
  us("TMO", "Thermo Fisher Scientific", "Health Care"),
  us("TJX", "TJX Companies", "Consumer Discretionary"),
  us("TKO", "TKO Group Holdings", "Communication Services"),
  us("TTD", "Trade Desk (The)", "Communication Services"),
  us("TSCO", "Tractor Supply", "Consumer Discretionary"),
  us("TT", "Trane Technologies", "Industrials"),
  us("TDG", "TransDigm Group", "Industrials"),
  us("TRV", "Travelers Companies (The)", "Financials"),
  us("TRMB", "Trimble Inc.", "Information Technology"),
  us("TFC", "Truist Financial", "Financials"),
  us("TYL", "Tyler Technologies", "Information Technology"),
  us("TSN", "Tyson Foods", "Consumer Staples"),
  us("USB", "U.S. Bancorp", "Financials"),
  us("UBER", "Uber", "Industrials"),
  us("UDR", "UDR, Inc.", "Real Estate"),
  us("ULTA", "Ulta Beauty", "Consumer Discretionary"),
  us("UNP", "Union Pacific Corporation", "Industrials"),
  us("UAL", "United Airlines Holdings", "Industrials"),
  us("UPS", "United Parcel Service", "Industrials"),
  us("URI", "United Rentals", "Industrials"),
  us("UNH", "UnitedHealth Group", "Health Care"),
  us("UHS", "Universal Health Services", "Health Care"),
  us("VLO", "Valero Energy", "Energy"),
  us("VEEV", "Veeva Systems", "Health Care"),
  us("VTR", "Ventas", "Real Estate"),
  us("VLTO", "Veralto", "Industrials"),
  us("VRSN", "Verisign", "Information Technology"),
  us("VRSK", "Verisk Analytics", "Industrials"),
  us("VZ", "Verizon", "Communication Services"),
  us("VRTX", "Vertex Pharmaceuticals", "Health Care"),
  us("VRT", "Vertiv", "Industrials"),
  us("VTRS", "Viatris", "Health Care"),
  us("VICI", "Vici Properties", "Real Estate"),
  us("V", "Visa Inc.", "Financials"),
  us("VST", "Vistra Corp.", "Utilities"),
  us("VMC", "Vulcan Materials Company", "Materials"),
  us("WRB", "W. R. Berkley Corporation", "Financials"),
  us("GWW", "W. W. Grainger", "Industrials"),
  us("WAB", "Wabtec", "Industrials"),
  us("WMT", "Walmart", "Consumer Staples"),
  us("DIS", "Walt Disney Company (The)", "Communication Services"),
  us("WBD", "Warner Bros. Discovery", "Communication Services"),
  us("WM", "Waste Management", "Industrials"),
  us("WAT", "Waters Corporation", "Health Care"),
  us("WEC", "WEC Energy Group", "Utilities"),
  us("WFC", "Wells Fargo", "Financials"),
  us("WELL", "Welltower", "Real Estate"),
  us("WST", "West Pharmaceutical Services", "Health Care"),
  us("WDC", "Western Digital", "Information Technology"),
  us("WY", "Weyerhaeuser", "Real Estate"),
  us("WSM", "Williams-Sonoma, Inc.", "Consumer Discretionary"),
  us("WMB", "Williams Companies", "Energy"),
  us("WTW", "Willis Towers Watson", "Financials"),
  us("WDAY", "Workday, Inc.", "Information Technology"),
  us("WYNN", "Wynn Resorts", "Consumer Discretionary"),
  us("XEL", "Xcel Energy", "Utilities"),
  us("XYL", "Xylem Inc.", "Industrials"),
  us("YUM", "Yum! Brands", "Consumer Discretionary"),
  us("ZBRA", "Zebra Technologies", "Information Technology"),
  us("ZBH", "Zimmer Biomet", "Health Care"),
  us("ZTS", "Zoetis", "Health Care"),
];
